# Generated by Django 3.0.4 on 2020-03-14 09:37

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=service.models.service_image_path)),
                ('created_at', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ('created_at',),
            },
        ),
    ]
